[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "b3_bem"
version = "0.1.0"
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "scipy",
    "CCBlade",
    # "ccblade @ file:///home/wr1/projects/CCBlade",
    "rich",
    "statesman @ git+https://github.com/wr1/statesman.git",
    "treeparse",
    "ruamel.yaml",
    "pydantic",
]

authors = [{name = "wr1", email = "8971152+wr1@users.noreply.github.com"}]



[project.scripts]
"b3_bem" = "b3_bem.cli.cli:main"

[tool.hatch.metadata]
allow-direct-references = true
